markdown: kramdown
remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme 
title: E-LAUTE
description: "Electronic Linked Annotated<br>Unified Tablature Edition"
repository: e-laute-test/e-laute-test.github.io
languages: ["en", "de"]
exclude_from_localization: ["javascript", "images", "css", "public"]
parallel_localization: false

presentation:
  de: Pr채sentation
  en: Presentation

project:
  de: Das Projekt
  en: The Project

news:
  de: News 
  en: News

edition:
  de: Edition
  en: Edition

team:
  de: Team
  en: Team

partner:
  de: Partner & Beratendes Gremium
  en: Partners & advisory panel

aspects: 
  de: Einzelne Aspekte
  en: Single aspects

single_presentations:
  de: Einzelne Pr채sentationen
  en: Single presentations

press:
  de: Presse 체ber uns
  en: Press about us

collab:
  de: Zur kollaborativen Edition
  en: Collaborative edition

sourcing:
  de: Stellenausschreibungen
  en: Sourcing

contact:
  de: Kontakt
  en: Contact

activity:
  de: Aktivit채ten
  en: Activities


collections:
  de:
    output: true
  en:
    output: true

research:
  de: Forschung
  en: Research
